server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
#        exclude: "env,beans"
    jmx:
      exposure:
        include: "health,info"

info:
  app:
    name: hello-actuator
    company: sj
  copyright: SJ

logging:
  level:
    hello.controller: debug